#!/usr/bin/env bash
# Call the function to retrieve DNS information
dns_look_up () {
	dig "$1" | grep -A1 "ANSWER SECTION:" | sed -r "s/$1./$2/g" | awk 'NR==2 {print "The subdomain " $1 " is a " $4 " record and points to "$5}'
}

if [ "$#" -eq 2 ]
then
    dns_look_up "$2.$1" "$2"
else
    dns_look_up "www.$1" 'www'
    dns_look_up "lb-01.$1" 'lb-01'
    dns_look_up "web-01.$1" 'web-01'
    dns_look_up "web-02.$1" 'web-02'
fi
