#!/usr/bin/env bash
# installing an nginx web server listening on port 80

sudo apt update -y
sudo apt install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
