#!/usr/bin/env bash
# configure / to echo hello world and /redirect_me to 301 moved permentely.

# updating the system and installing nginx.
sudo apt -y update
sudo apt install -y nginx

# configuring root /
echo "Hello World!" | sudo tee /var/www/html/index.html

# configure /redirect_me.
sudo sed -i "server_name _;/a \n\tlocation /redirect_me {\n\t\t rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}" /etc/nginx/sites_availble
