#!/usr/bin/env bash
# configuring main / and /redirect_me and /not_found

# updating system and installing nginx
sudo apt -y update
sudo apt install -y nginx
sudo ufw allow 'Nginx http'

# configuring the main location.
echo "Hello World!" | sudo tee /var/www/html/index.html

# configuring /redirect_me
sudo sed -i "server_name _;/a \tlocation /redirect_me {\n\t rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}" /etc/nginx/sites-available

# configuring 404 not_found


