#!/usr/bin/env bash
# install and configure nginx to listen on port 80.

sudo apt -y update
sudo apt -y install nginx

mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/not_found.html

server="server {
    server_name default;
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html/index.html;
    index index.html index.htm;
    location /redirect_me {
        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }

    error_page 404 /not_found.html;
}"

echo -e "$server" | sudo tee ~/testing

sudo service nginx service
