#!/usr/bin/env bash
# install and configure nginx to listen on port 80.

sudo apt -y update
sudo apt -y install nginx

mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/not_found.html

server="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://youtube.com/;
    }

    error_page 404 /custom404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}"

echo -e "$server" | sudo tee /etc/nginx/sites-available/default

sudo service nginx reload
