#!/usr/bin/env bash
# Create a dump file to archive db.

MYSQL_ROOT_PASSWORD="$1"
BACKUP_FILENAME="backup.sql"
DATE=$(date +'%d-%m-%Y')
mysqldump -u root -p$MYSQL_ROOT_PASSWORD --all-databases > "$BACKUP_FILENAME"
tar -cvzf "$DATE.tar.gz" "$SQLDUMP_FILE"
