#!/usr/bin/env bash
# making sure nginx installed

sudo apt -y update
sudo apt install -y nginx
sudo service start nginx
# stopping whatever listnenig on port 80 and restarting nginx

# finding service listnenig on port 80
service=$(sudo lsof -i :80 | awk 'NR>1{print $1}' | uniq)

# stopping the service 
if [ -n "$service" ]; then
	systemctl stop "$service"
fi

# restarting nginx
service nginx restart
