#!/usr/bin/env bash
# displayin 12 hours clock

hours=0
minute=1

while ((hours <= 12))
do
	echo "Hour: $hours"
	while ((minute <= 59))
	do
		echo $minute
		((minute++))
	done
	minute=1
	((hours++))
done
