#!/usr/bin/env bash
# Use 'ip' command instead of 'ifconfig' if it's available
command -v ip >/dev/null 2>&1 && cmd="ip -4 addr show" || cmd="ifconfig"
# Extract and display IPv4 addresses using grep and awk
$cmd | grep -oE 'inet ([0-9]{1,3}\.){3}[0-9]{1,3}' | awk '{print $2}'

