#!/usr/bin/env bash
# configure nginx to run as nginx user and listen on port 8080

pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
