#!/usr/bin/env bash

# getting the private_key
private_key='~/.ssh/school'

# Set the target server's IP address or hostname
server="server01"

# establishing the connection
ssh -i "$private_key" ubuntu@"$server"
