#!/usr/bin/env bash

# Set the private key file
private_key="~/.ssh/school"

# Set the target server's IP address or hostname
server="server01"

# Use SSH with the specified private key and user
ssh -i "$private_key" ubuntu@"$server"

